### ISSUE TITLE
cryptic error: invalid dereferences (`*<Expr>`) panic with `should not happen`

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#1088]
Example:

```go
package main

func main() {
	v := 1
	println(*v)
}
```

```
panic: should not happen [recovered]
        panic: main/a.gno:5: should not happen

goroutine 1 [running]:
github.com/gnolang/gno/gnovm/pkg/gnolang.Preprocess.func2.1()
        /home/howl/oc/gno/gnovm/pkg/gnolang/preprocess.go:173 +0x46d
panic({0xbf0b00, 0xf4e3c0})
        /usr/lib/go/src/runtime/panic.go:890 +0x263
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).doOpStaticTypeOf(0xc0002a6b40)
        /home/howl/oc/gno/gnovm/pkg/gnolang/op_types.go:493 +0x3d39
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).Run(0xc0002a6b40)
        /home/howl/oc/gno/gnovm/pkg/gnolang/machine.go:1280 +0xdce
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).EvalStaticTypeOf(0xc0002a6b40, {0xf62ed8, 0xc000580c00}, {0xf5cf68?, 0xc0002b9d70})
        /home/howl/oc/gno/gnovm/pkg/gnolang/machine.go:768 +0x335
```

"should not happen" messages should IMO be reserved for cases in which, even for incorrect code, the given branch should not be reachable.

**Comment by Villaquiranm** [comment]
this was changed on #2051 
- panic("should not happen")
+ panic("unexpected star expression")
