### ISSUE TITLE
Runtime Panic in `gno` when Built with `-trimpath` build flag due to Amino Package Path Resolution

### ISSUE THREAD

**Issue by gfanton** [gnolang/gno#1236]
### Description
Using the `-trimpath` build flag with `gno` results in a runtime panic.

### Environment
- **OS:** macOS Sonoma 14.0
- **gno Version:** master
- **commit:** tested on b34816b491bbc570a7737d8c70df9bf63f19ca96

### Steps to Reproduce
```sh
# Navigate to gnovm directory within the gno repository
$ cd gnovm

# Manually build the gno binary using the `-trimpath` flag
$ go build -trimpath -o build/gno ./cmd/gno

# Run the gno binary
$ ./build/gno
```

### Expected Behaviour
All `gno` commands should run as intended without any errors.

### Actual Behaviour
`gno` encounters a panic.

### Logs
```
panic: dirName, if present, should be absolute, but received: github.com/gnolang/gno/tm2/pkg/crypto/multisig

goroutine 1 [running]:
github.com/gnolang/gno/tm2/pkg/amino/pkg.assertValidDirName({0x1057c2a99?, 0x2?})
	github.com/gnolang/gno/tm2/pkg/amino/pkg/pkg.go:356 +0x174
github.com/gnolang/gno/tm2/pkg/amino/pkg.NewPackage({0x105309e57, 0x2e}, {0x1052e3b13, 0x2}, {0x1057c2a99, 0x2e})
	github.com/gnolang/gno/tm2/pkg/amino/pkg/pkg.go:73 +0x90
github.com/gnolang/gno/tm2/pkg/amino.NewPackage(...)
	github.com/gnolang/gno/tm2/pkg/amino/amino.go:883
github.com/gnolang/gno/tm2/pkg/crypto/multisig.init()
```

### Possible Cause & Solution
The underlying issue appears to be a side effect of the `amino` package using the call stack to obtain an absolute path of the current directory. As this behavior is triggered implicitly without a direct call (siimply by importing the package) it might be challenging to fix. 

A code snippet showcasing the implicit behavior:
```go
// gnolang/gno/tm2/pkg/bitarray
package bitarray

import "github.com/gnolang/gno/tm2/pkg/amino"

var Package = amino.RegisterPackage(amino.NewPackage(
	"github.com/gnolang/gno/tm2/pkg/bitarray",
	"tm",
	amino.GetCallersDirname(), // <<<< HERE
).WithDependencies().WithTypes(
	BitArray{}, "BitArray",
))
```

We cannot pass variables, except perhaps through environment variables like `GNOROOT`. However, it's undesirable for `tm2` to be dependent on such a variable.

**Comment by notJoon** [comment]
I've confirmed that this issue can no longer be reproduced. It seems fine to close the issue.
<img width="855" height="520" alt="Image" src="https://github.com/user-attachments/assets/e182b094-b033-4433-a378-88fcd856991b" />

**Comment by nemanjantic** [comment]
Closing - @notJoon was unable to reproduce
