### ISSUE TITLE
type assertion on recovered `nil`s panics

### ISSUE THREAD

**Issue by thehowl** [gnolang/gno#1650]
```go
package main

type ex int

func (ex) Error() string { return "" }

func main() {
	defer func() {
		e := recover()
		if _, ok := e.(ex); ok {
			println("wat")
		} else {
			println("ok")
		}
	}()
}
```

<details><summary>Output and stacktrace</summary>
<p>

```
panic running expression main(): runtime error: invalid memory address or nil pointer dereference
Machine:
    CheckTypes: false
	Op: [OpHalt OpReturnFromBlock OpReturnCallDefers OpBody OpPopBlock OpIfCond OpEval OpDefine]
	Values: (len: 3)
          #2 (typeval{main.ex (0xc000119440)} type{})
          #1 (undefined)
          #0 (main func()())
	Exprs:
          #0 ok<VPBlock(1,0)>
	Stmts:
          #1 _<VPBlock(0,0)>, ok<VPBlock(1,0)> := e<VPBlock(2,0)>.(ex<VPBlock(5,0)>)
          #0 bodyStmt[0/0/2]=(end)
	Blocks:
          @(1) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc00035e960,Source:if _<VPBlock(0,0)>, ok<VPBlock(1...,Parent:0xc00035e5a0)
            ok: (undefined)
 (s vals) @(1) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc000266d20,Source:if _<VPBlock(0,0)>, ok<VPBlock(1...,Parent:0xc000344020)
            ok: (false bool)
 (s typs) @(1) [bool]
          @(2) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc00035e5a0,Source:func func(){ e<VPBlock(1,0)> := ...,Parent:0xc00035e3c0)
            e: (undefined)
 (s vals) @(2) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc000344020,Source:func func(){ e<VPBlock(1,0)> := ...,Parent:0xc000335420)
            e: (undefined)
 (s typs) @(2) [interface{}]
          @(3) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc00035e3c0,Source:func main() { defer func func(){...,Parent:0xc00035e000)
 (s vals) @(3) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc000335420,Source:func main() { defer func func(){...,Parent:0xc0002cf820)
 (s typs) @(3) []
          @(4) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc00035e000,Source:file{ package main; type ex (con...,Parent:0xc0002ca5a0)
 (s vals) @(4) Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc0002cf820,Source:file{ package main; type ex (con...,Parent:0xc0002cfb20)
 (s typs) @(4) []
          @(5) main
	Blocks (other):
          #2 Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc00035e5a0,Source:func func(){ e<VPBlock(1,0)> := ...,Parent:0xc00035e3c0)
            e: (undefined)
 (static) #2 Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc000344020,Source:func func(){ e<VPBlock(1,0)> := ...,Parent:0xc000335420)
            e: (undefined)
          #1 Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc00035e3c0,Source:func main() { defer func func(){...,Parent:0xc00035e000)
 (static) #1 Block(ID:0000000000000000000000000000000000000000:0,Addr:0xc000335420,Source:func main() { defer func func(){...,Parent:0xc0002cf820)
	Frames:
          #0 [FRAME FUNC:main RECV:(undefined) (0 args) 1/0/0/0/1 LASTPKG:main LASTRLM:Realm(nil)]
	Realm:
	  
	Exceptions:
	  []
	  
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0xa1ac29]

goroutine 1 [running]:
main.runExpr.func1()
	/home/howl/oc/gno/gnovm/cmd/gno/run.go:159 +0x125
panic({0xbcb520?, 0x135cc90?})
	/usr/lib/go/src/runtime/panic.go:914 +0x21f
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).doOpTypeAssert2(0xc000166fc0)
	/home/howl/oc/gno/gnovm/pkg/gnolang/op_expressions.go:318 +0x5a9
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).Run(0xc000166fc0)
	/home/howl/oc/gno/gnovm/pkg/gnolang/machine.go:1265 +0xd8e
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).Eval(0xc000166fc0, {0xe7fb18, 0xc000119860})
	/home/howl/oc/gno/gnovm/pkg/gnolang/machine.go:701 +0x579
main.runExpr(0xc000166fc0, {0xc9823d?, 0x1?})
	/home/howl/oc/gno/gnovm/cmd/gno/run.go:166 +0x8d
main.execRun(0xc000291770, {0xc0002e9fc0, 0x1, 0x1}, {0xe82030, 0xc0002f6d70})
	/home/howl/oc/gno/gnovm/cmd/gno/run.go:108 +0x3b7
main.newRunCmd.func1({0x0?, 0xc0000341a0?}, {0xc0002e9fc0?, 0x0?, 0x0?})
	/home/howl/oc/gno/gnovm/cmd/gno/run.go:35 +0x30
github.com/gnolang/gno/tm2/pkg/commands.(*Command).Run(0xc0002f4fd0?, {0xe79468?, 0x13b1200?})
	/home/howl/oc/gno/tm2/pkg/commands/command.go:247 +0x19d
github.com/gnolang/gno/tm2/pkg/commands.(*Command).Run(0xc0002f4790?, {0xe79468?, 0x13b1200?})
	/home/howl/oc/gno/tm2/pkg/commands/command.go:251 +0x149
github.com/gnolang/gno/tm2/pkg/commands.(*Command).ParseAndRun(0xc0002f4b00?, {0xe79468, 0x13b1200}, {0xc000034190?, 0xc0002f4bb0?, 0xc0002f4c60?})
	/home/howl/oc/gno/tm2/pkg/commands/command.go:132 +0x49
github.com/gnolang/gno/tm2/pkg/commands.(*Command).Execute(0xe82030?, {0xe79468?, 0x13b1200?}, {0xc000034190?, 0x13276c8?, 0xc0000061a0?})
	/home/howl/oc/gno/tm2/pkg/commands/command.go:114 +0x29
main.main()
	/home/howl/oc/gno/gnovm/cmd/gno/main.go:13 +0x5f
```

</p>
</details> 

Note: this is not about asserting on `nil` in general; I suspect there's as always the internal pesky difference between an "initialised" and an "uninitialised" value. This code works:

```go
package main

type ex int

func (ex) Error() string { return "" }

func main() {
	var i interface{}
	if _, ok := i.(ex); ok {
		println("wat")
	} else {
		println("ok")
	}
}

```

**Comment by deelawn** [comment]
I was working on a fix for this and may have one, but encountered a separate issue while testing -- #1656.  It would be good to get this fixed first so that any tests added along with this fix are certain to behave correctly.
