### ISSUE TITLE
Using range with Number Causes VM Panic in Gno

### ISSUE THREAD

**Issue by omarsy** [gnolang/gno#3328]
#### Description
The following code snippet causes a panic in Gno but works as expected in Go:

```go
package main

import (
	"fmt"
)

func main() {
	for i := range(3) {
		fmt.Println("Hello", i)
	}
}
```

#### Expected Behavior
The code should iterate over the range of numbers from `0` to `3` and print the message `"Hello"` along with the current value of `i`. This is the behavior observed in Go.

#### Actual Behavior
In Gno, the code causes a VM panic. It seems that the `range` expression is not being handled in the same way as in Go, where it is expected to iterate over the sequence `[0,1,2]`.

####  Stacktrace
```

files_test.go:92: unexpected panic: unexpected type for len(): <untyped> bigint
        output:
        
        stack:
        goroutine 50 [running]:
        runtime/debug.Stack()
                /Users/ghost/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.darwin-arm64/src/runtime/debug/stack.go:24 +0x64
        github.com/gnolang/gno/gnovm/pkg/test.(*TestOptions).runTest.func1()
                /Users/ghost/Documents/projects/teritori/gno/gnovm/pkg/test/filetest.go:196 +0xac
        panic({0x100c9e260?, 0x140002da050?})
                /Users/ghost/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.darwin-arm64/src/runtime/panic.go:770 +0x124
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).Run.func1()
                /Users/ghost/Documents/projects/teritori/gno/gnovm/pkg/gnolang/machine.go:1139 +0xac
        panic({0x100c9e260?, 0x140002da050?})
                /Users/ghost/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.darwin-arm64/src/runtime/panic.go:770 +0x124
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*TypedValue).GetLength(0x100d995d0?)
                /Users/ghost/Documents/projects/teritori/gno/gnovm/pkg/gnolang/values.go:2126 +0x404
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).doOpExec(0x140000e8008, 0x8?)
                /Users/ghost/Documents/projects/teritori/gno/gnovm/pkg/gnolang/op_exec.go:154 +0x1218
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).Run(0x140000e8008)
                /Users/ghost/Documents/projects/teritori/gno/gnovm/pkg/gnolang/machine.go:1456 +0xb34
        github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).RunStatement(0x140000e8008, {0x100d9f360, 0x140002acc80})
                /Users/ghost/Documents/projects/teritori/gno/gnovm/pkg/gnolang/machine.go:800 +0x330
        github.com/gnolang/gno/gnovm/pkg/test.(*TestOptions).runTest(0x140004626e0, 0x140000e8008, {0x100a121c0, 0x4}, {0x1400043d210, 0x10}, {0x14000191000, 0x79, 0x140001a0280?})
                /Users/ghost/Documents/projects/teritori/gno/gnovm/pkg/test/filetest.go:223 +0x578
        github.com/gnolang/gno/gnovm/pkg/test.(*TestOptions).runFiletest(0x140004626e0, {0x1400043d210, 0x10}, {0x14000191000, 0x79, 0x200})
                /Users/ghost/Documents/projects/teritori/gno/gnovm/pkg/test/filetest.go:68 +0x50c
        github.com/gnolang/gno/gnovm/pkg/test.(*TestOptions).RunFiletest(...)
                /Users/ghost/Documents/projects/teritori/gno/gnovm/pkg/test/filetest.go:28
        github.com/gnolang/gno/gnovm/pkg/gnolang_test.TestFiles.func2.2(0x1400046e000)
                /Users/ghost/Documents/projects/teritori/gno/gnovm/pkg/gnolang/files_test.go:90 +0xfc
        testing.tRunner(0x1400046e000, 0x1400019efc0)
                /Users/ghost/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.darwin-arm64/src/testing/testing.go:1689 +0xec
        created by testing.(*T).Run in goroutine 34
                /Users/ghost/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.darwin-arm64/src/testing/testing.go:1742 +0x318
```

**Comment by thehowl** [comment]
This is a new Go feature. We're lagging behind on many (more important) features, so I don't properly see this as a priority. (generics, `any`, `min`/`max`, ...)

**Comment by thehowl** [comment]
Let's revisit another time.

**Comment by omarsy** [comment]
Maybe we should raise an error on the preprocess part instead of runtime panic same for the min max
