### ISSUE TITLE
gnovm/pkg/transpiler: mangled imports in Gno code cause a panic when generating Go code

### ISSUE THREAD

**Issue by odeke-em** [gnolang/gno#3425]
### Description

In furtherance of https://github.com/gnolang/gno/issues/3087, I am fuzzing and investigating the transpiler and when presented with this Gno program

```go
package A
import(""//"
""/***/)
```

Passing it into the transpiler results in this panic
```shell
panic: invalid line number 5 (should be < 5) [recovered]
	panic: invalid line number 5 (should be < 5)

goroutine 26 [running]:
github.com/gnolang/gno/gnovm/pkg/transpiler.Transpile.func1()
	/home/emmanuel/go/src/github.com/gnolang/gno/gnovm/pkg/transpiler/transpiler.go:131 +0xae
panic({0xb30640?, 0xc0001246c0?})
	/home/emmanuel/go/src/go.googlesource.com/go/src/runtime/panic.go:787 +0x132
go/token.(*File).MergeLine(0xc00028e300, 0x63?)
	/home/emmanuel/go/src/go.googlesource.com/go/src/go/token/position.go:157 +0x1a8
go/ast.sortSpecs(0xc00025e080, 0xc0006c4dc0, {0xc000126e80, 0x2, 0x2})
	/home/emmanuel/go/src/go.googlesource.com/go/src/go/ast/import.go:210 +0xa54
go/ast.SortImports(0xc00025e080, 0xc0006c4dc0)
	/home/emmanuel/go/src/go.googlesource.com/go/src/go/ast/import.go:40 +0x5a7
go/format.Node({0xe56460, 0xc0006a5740}, 0xc00025e080, {0xb6d720?, 0xc0006c4be0?})
	/home/emmanuel/go/src/go.googlesource.com/go/src/go/format/format.go:81 +0x286
github.com/gnolang/gno/gnovm/pkg/transpiler.Transpile({0xc00044f000, 0x1f}, {0xc2c171, 0x3}, {0xc2d99e, 0x6})
	/home/emmanuel/go/src/github.com/gnolang/gno/gnovm/pkg/transpiler/transpiler.go:134 +0x5ef
```

where it tried to generate this Go code
```go
// Code generated by github.com/gnolang/gno. DO NOT EDIT.

//go:build gno

//line in.gno:1:1
```

### Expected behaviour

Not a panic

Kindly cc-ing @petar-dambovaliev @moul @jaekwon

**Comment by kristovatlas** [comment]
@odeke-em Thank you for submitting. It's an interesting bug, but I don't see an obvious security implication yet so I haven't processed it as a security-related bug.

**Comment by odeke-em** [comment]
The error message has changed but has gotten much worse now as of head commit e352770149c631c529e380ba2cdfe785878ff629 and more obscure with `panic: expected package name [a] but got [A]`

```shell
$ gno run 3425.gno 
panic: expected package name [a] but got [A]

goroutine 1 [running]:
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).runFileDecls(0xc000370008, {0xc00011c038, 0x1, 0x1})
	/Users/emmanuelodeke/go/src/github.com/gnolang/gno/gnovm/pkg/gnolang/machine.go:479 +0x814
github.com/gnolang/gno/gnovm/pkg/gnolang.(*Machine).RunFiles(0xc000370008, {0xc00011c038?, 0x0?, 0x4b8ea68?})
	/Users/emmanuelodeke/go/src/github.com/gnolang/gno/gnovm/pkg/gnolang/machine.go:422 +0x2e
main.execRun(0xc0003f9080, {0xc0003be0d0, 0x1, 0x1}, {0x4ba6f50, 0xc0003d1720})
	/Users/emmanuelodeke/go/src/github.com/gnolang/gno/gnovm/cmd/gno/run.go:138 +0x4ea
main.newRunCmd.func1({0x4a93fc0?, 0xc000032500?}, {0xc0003be0d0?, 0xc000480fc0?, 0x0?})
	/Users/emmanuelodeke/go/src/github.com/gnolang/gno/gnovm/cmd/gno/run.go:39 +0x30
github.com/gnolang/gno/tm2/pkg/commands.(*Command).Run(0xc0000dd680?, {0x4b984d0?, 0x5301a00?})
	/Users/emmanuelodeke/go/src/github.com/gnolang/gno/tm2/pkg/commands/command.go:265 +0x192
github.com/gnolang/gno/tm2/pkg/commands.(*Command).Run(0xc0000dd680?, {0x4b984d0?, 0x5301a00?})
	/Users/emmanuelodeke/go/src/github.com/gnolang/gno/tm2/pkg/commands/command.go:269 +0x13e
github.com/gnolang/gno/tm2/pkg/commands.(*Command).ParseAndRun(0xc0000dd680, {0x4b984d0, 0x5301a00}, {0xc0000324f0?, 0xc0000dd8c0?, 0xc0000dd980?})
	/Users/emmanuelodeke/go/src/github.com/gnolang/gno/tm2/pkg/commands/command.go:150 +0x49
github.com/gnolang/gno/tm2/pkg/commands.(*Command).Execute(0x4ba6f50?, {0x4b984d0?, 0x5301a00?}, {0xc0000324f0?, 0x524c168?, 0xc000002380?})
	/Users/emmanuelodeke/go/src/github.com/gnolang/gno/tm2/pkg/commands/command.go:127 +0x2c
main.main()
	/Users/emmanuelodeke/go/src/github.com/gnolang/gno/gnovm/cmd/gno/main.go:13 +0x5f
```

**Comment by thehowl** [comment]
Not highly relevant, as it doesn't create issues on production which aren't catchable by the type checker; worth fixing in the future.
