### ISSUE TITLE
Tests do not hold unique TCP ports

### ISSUE THREAD

**Issue by zivkovicmilos** [gnolang/gno#508]
### Description

Tests like [ExampleHTTP_simple](https://github.com/gnolang/gno/blob/eb3c058dde12b61dba40317713f75ad0ab302dec/pkgs/bft/rpc/client/examples_test.go#L13) and [ExampleHTTP_batch](https://github.com/gnolang/gno/blob/eb3c058dde12b61dba40317713f75ad0ab302dec/pkgs/bft/rpc/client/examples_test.go#L63) can cause the workflows to fail at certain times, because they start Tendermint nodes that  try to listen on an address + port combination that is already taken (by another test?).

### Your environment

* macOS 13.1
* latest version of the master branch
* master branch, eb3c058dde12b61dba40317713f75ad0ab302dec

### Steps to reproduce

Not sure how to locally reproduce this, as locally I've never encountered this issue.

I've encountered this issue on a multitude of GitHub workflow runs, and exclusively for `test.go3`. Rerunning the workflow forces it to pass.

### Expected behaviour

Tests should utilize unique address and port combos.

### Actual behaviour

Tendermint address and port combos are not unique.

### Logs

Example workflow run:
```
2023-01-16T21:57:11.1775102Z --- FAIL: ExampleHTTP_batching (0.00s)
2023-01-16T21:57:11.1804906Z panic: listen tcp 0.0.0.0:35697: bind: address already in use [recovered]
2023-01-16T21:57:11.1806070Z 	panic: listen tcp 0.0.0.0:35697: bind: address already in use
2023-01-16T21:57:11.1806877Z 
2023-01-16T21:57:11.1807560Z goroutine 1 [running]:
2023-01-16T21:57:11.1808794Z testing.(*InternalExample).processRunResult(0xc0006abbe8, {0x0, 0x0}, 0xc0006ab7a0?, 0x0, {0xabc2c0, 0xc001423720})
2023-01-16T21:57:11.1809332Z 	/opt/hostedtoolcache/go/1.18.9/x64/src/testing/example.go:91 +0x4e5
2023-01-16T21:57:11.1809716Z testing.runExample.func2()
2023-01-16T21:57:11.1810151Z 	/opt/hostedtoolcache/go/1.18.9/x64/src/testing/run_example.go:59 +0x11c
2023-01-16T21:57:11.1810513Z panic({0xabc2c0, 0xc001423720})
2023-01-16T21:57:11.1810906Z 	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/panic.go:838 +0x207
2023-01-16T21:57:11.1817290Z github.com/gnolang/gno/pkgs/bft/rpc/test.StartTendermint({0xc5abd0, 0xc000d46940}, {0xc0006aba38, 0x2, 0x4689ee?})
2023-01-16T21:57:11.1818291Z 	/home/runner/work/gno/gno/pkgs/bft/rpc/test/helpers.go:107 +0xff
2023-01-16T21:57:11.1818967Z github.com/gnolang/gno/pkgs/bft/rpc/client_test.ExampleHTTP_batching()
2023-01-16T21:57:11.1819368Z 	/home/runner/work/gno/gno/pkgs/bft/rpc/client/examples_test.go:66 +0x8b
2023-01-16T21:57:11.1819677Z testing.runExample({{0xb56cb7, 0x14}, 0xb9a260, {0xb694d4, 0x28}, 0x0})
2023-01-16T21:57:11.1820023Z 	/opt/hostedtoolcache/go/1.18.9/x64/src/testing/run_example.go:63 +0x28d
2023-01-16T21:57:11.1820326Z testing.runExamples(0xc0006abdd8, {0x1058860?, 0x2, 0x16?})
2023-01-16T21:57:11.1821011Z 	/opt/hostedtoolcache/go/1.18.9/x64/src/testing/example.go:44 +0x186
2023-01-16T21:57:11.1821253Z testing.(*M).Run(0xc00023d360)
2023-01-16T21:57:11.1821546Z 	/opt/hostedtoolcache/go/1.18.9/x64/src/testing/testing.go:1721 +0x689
2023-01-16T21:57:11.1821858Z github.com/gnolang/gno/pkgs/bft/rpc/client_test.TestMain(0x442271?)
2023-01-16T21:57:11.1822186Z 	/home/runner/work/gno/gno/pkgs/bft/rpc/client/main_test.go:24 +0x85
2023-01-16T21:57:11.1822425Z main.main()
2023-01-16T21:57:11.1822630Z 	_testmain.go:97 +0x1d3
2023-01-16T21:57:11.1834469Z FAIL	github.com/gnolang/gno/pkgs/bft/rpc/client	4.863s
```

### Proposed solution

I'm suspecting that the port is initially free, but gets taken up before the Tendermint node is started further down in the call stack. No proposed solution for now, we still need to investigate how this port gets taken up in the meantime as these tests aren't running in parallel

**Comment by tbruyelle** [comment]
I encountered this issue multiple times when using the cosmos-sdk `testutil` packages. The common point between this package and the one used in gno, is they try to find a free port using the stdlib `net` package (see `pkgs/os/net.GetFreePort()` func), but sometimes the port isn't actually free.

Although I didn't find a way to fix it, I suspect this is because of the github action environment, that picks the same port in the time between `GetFreePort` and its usage.

**Comment by thehowl** [comment]
I think the problem is that GetFreePort, in order to determine a free port, is actually doing a `net.Listen` on the 0 port. Which by documented behaviour of the net package, finds an open port, and then immediately closes the port. A better way is to instead of determining an open port and listening on that port, just listening on port 0 (and then adjusting any other addresses with the effective port of the connection). The reason why it might fail here on repeated usage may have to do with kernel internals (ie. for a short (0-5ms) while after the conn is closed, it is closed but not ready to be used again)

I'm trying to see if tests succeed removing all GetFreePort and replacing with a 0 port. Will probably open a PR on monday to attempt to fix this.
